services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/app
    image: ticket-price-bot:0.1.a
    stdin_open: true
    tty: true

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    image: ticket-price-bot:0.1.a-dev
    stdin_open: true
    tty: true
